/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjetoDto { 
    idProjeto: number;
    titulo: string;
    eventosNoQualParticipa: Array<number>;
    membrosProjeto: Array<number>;
}

