/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfoPessoaSimplesDto } from './infoPessoaSimplesDto';
import { Periodo } from './periodo';


export interface EventoDto { 
    idEvento: number;
    titulo: string;
    descricao: string;
    periodos: Array<Periodo>;
    supervisores: Array<InfoPessoaSimplesDto>;
    projetosParticipantes: Array<number>;
}

